/* Generated by scripts/write_docs_ref.py — do not edit. */
window.TAXTRIAGE_DOCS = {
  "ref": "main",
  "version": "main",
  "label": "development",
  "commit": "c6fd48230ce77e613e062a50b0581416102cf49a"
};
